[package]
name = "timed"
version = "0.1.0"
authors = ["Manuel Woelker <github@manuel.woelker.org>"]

[dependencies]
futures = "0.1"
tokio-core = "0.1"
tokio-service = "0.1"
tokio-proto = "0.1"
byteorder = "1"
time = "0.1"